/**
 * Combines HSK 2–6 migration files into one SQL file for a single SQL Editor run.
 * Run: npm run db:combine-hsk
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const MIGRATIONS = [
  "20260703000000_hsk2.sql",
  "20260704000000_hsk3.sql",
  "20260705000000_hsk4.sql",
  "20260706000000_hsk5.sql",
  "20260707000000_hsk6.sql",
];

const dir = join(process.cwd(), "supabase/migrations");
const parts = MIGRATIONS.map((file) => {
  const path = join(dir, file);
  return `-- ========== ${file} ==========\n${readFileSync(path, "utf8")}`;
});

const out = join(dir, "_combined_hsk2-6.sql");
writeFileSync(
  out,
  [
    "-- Combined HSK 2–6 migrations",
    "-- Generated by npm run db:combine-hsk",
    "-- Paste this entire file into the Supabase SQL Editor and run once.",
    "-- Requires Starter + HSK 1 content to already exist.",
    "",
    ...parts,
  ].join("\n"),
  "utf8"
);

console.log(`Wrote ${out} (${(readFileSync(out).length / 1024 / 1024).toFixed(1)} MB)`);
